### ISSUE TITLE
Unable to verify

### ISSUE THREAD

**Issue by mumbaigirl** [maharanasarkar/rasa-whatsapp_connector#6]
```
endpoints.yml

#  wait_time_between_pulls:  10   # [optional](default: 100)

#Server which runs your custom actions.
#https://rasa.com/docs/rasa/custom-actions

action_endpoint:
  url: "http://localhost:5055/webhook"

# Tracker store which is used to store the conversations.
# By default the conversations are stored in memory.
# https://rasa.com/docs/rasa/tracker-stores

#tracker_store:
#    type: redis
#    url: <host of the redis instance, e.g. localhost>
#    port: <port of your redis instance, usually 6379>
#    db: <number of your database within redis, e.g. 0>
#    password: <password used for authentication>
#    use_ssl: <whether or not the communication is encrypted, default false>

#tracker_store:
#    type: mongod
#    url: <url to your mongo instance, e.g. mongodb://localhost:27017>
#    db: <name of the db within your mongo instance, e.g. rasa>
#    username: <username used for authentication>
#    password: <password used for authentication>

# Event broker which all conversation events should be streamed to.
# https://rasa.com/docs/rasa/event-brokers

#event_broker:
#  url: localhost
#  username: username
#  password: password
#  queue: queue
custom_whatsapp_connector.CustomWhatsAppInput:
  webhook_url: "http://mydomain:5056/webhooks/whatsapp/webhook"
```

#**Also, I tried the below configurations**
```
#custom_whatsapp_connector.CustomWhatsAppInput:
# webhook_url: "http://mydomain:5056/webhook"
#custom_whatsapp_connector.CustomWhatsAppInput:
# webhook_url: "http://mydomain/webhook"
```

```
credentials.yml
# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/messaging-and-voice-channels

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


#facebook:
#  verify: "<verify>"
#  secret: "<your secret>"
#  page-access-token: "<your page access token>"

  whatsapp:
  auth_token: "my auth token from meta goes here"
  phone_number_id: "54555455"
  verify_token: "12349"

#slack:
#  slack_token: "<your slack token>"
#  slack_channel: "<the slack channel>"
#  slack_signing_secret: "<your slack signing secret>"

#socketio:
#  user_message_evt: <event name for user message>
#  bot_message_evt: <event name for bot messages>
#  session_persistence: <true/false>

#mattermost:
#  url: "https://<mattermost instance>/api/v4"
#  token: "<bot token>"
#  webhook_url: "<callback URL>"

# This entry is needed if you are using Rasa Enterprise. The entry represents credentials
# for the Rasa Enterprise "channel", i.e. Talk to your bot and Share with guest testers.
rasa:
  url: "http://localhost:5002/api"

Below is where I kept whatsapp.py
```
![Screenshot 2024-03-08 033329](https://github.com/maharanasarkar/whatsapp-connector-rasa/assets/99070985/04032cd5-14f1-40b4-b3ec-6d2ae5127f0e)

I tried below two variations, , but could not connect it with Meta, I think something is wrong with my webhook URL structure
![Screenshot 2024-03-08 032745](https://github.com/maharanasarkar/whatsapp-connector-rasa/assets/99070985/42050c38-23f7-4c6c-a01f-c3682fffecee)
![Screenshot 2024-03-08 032733](https://github.com/maharanasarkar/whatsapp-connector-rasa/assets/99070985/3199c397-606a-4dc7-a942-129d500c687d)

Kindly help.
